owner: hra42
repo: postrausch-uptime

sites:
  - name: Server Status V4
    check: "tcp-ping"
    url: $SERVER_IP_V4
    port: $SERVER_PORT
  - name: Server Status V6
    check: "tcp-ping"
    url: $SERVER_IP_V6
    port: $SERVER_PORT

assignees:
  - hra42

status-website:
  cname: status.postrausch.tech
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Postrausch Uptime Monitor
  introTitle: "Postrausch Uptime Monitor"
  introMessage: "Monitor the availability of our websites and services"
  theme: "night"
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
      robotsText: "noindex"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: hra42/uptime-monitor
