owner: hra42
repo: postrausch-uptime

sites:
  - name: Server Status
    check: "tcp-ping"
    url: $SERVER_IP_V4
    port: $SERVER_PORT
  - name: Website
    url: https://postrausch.tech
  - name: Blog Landing Page
    url: https://blog.postrausch.tech
    expectedStatusCodes:
      - 301
  - name: Blog - De
    url: https://de.blog.postrausch.tech
  - name: Blog - En
    url: https://en.blog.postrausch.tech

assignees:
  - hra42

status-website:
  cname: status.postrausch.tech
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Postrausch Uptime Monitor
  introTitle: "Postrausch Uptime Monitor"
  introMessage: "Monitor the availability of our websites and services"
  theme: "night"
  metaTags:
    - name: "color-scheme"
      content: "night"
    - name: "robots"
      content: "noindex"
      robotsText: "noindex"
  navbar:
    - title: Status
      href: /
    - title: Blog
      href: https://blog.postrausch.tech
    - title: Imprint
      href: https://postrausch.tech/impressum
    - title: Privacy Policy
      href: https://postrausch.tech/datenschutz
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: hra42-uptime-monitor

i18n:
  footer: "Postrausch Uptime Monitor is powered by <a href='https://upptime.js.org' target='_blank'>Upptime</a>."
