owner: hra42
repo: postrausch-uptime

sites:
  - name: Server Status
    check: "tcp-ping"
    url: $SERVER_IP_V4
    port: $SERVER_PORT

assignees:
  - hra42

status-website:
  cname: status.postrausch.tech
  logoUrl: https://public-files.postrausch.tech/Postrausch_Logo.png
  favicon: https://public-files.postrausch.tech/Postrausch_Logo.png
  name: Postrausch Uptime Monitor
  introTitle: "Postrausch Uptime Monitor"
  introMessage: "Monitor the availability of our websites and services"
  theme: "night"
  metaTags:
    - name: "color-scheme"
      content: "night"
    - name: "robots"
      content: "noindex"
      robotsText: "noindex"
  navbar:
    - title: Status
      href: /
    - title: Blog
      href: https://blog.postrausch.tech
    - title: Imprint
      href: https://postrausch.tech/impressum
    - title: Privacy Policy
      href: https://postrausch.tech/datenschutz
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: hra42-uptime-monitor

i18n:
  footer: "Postrausch Uptime Monitor is powered by <a href='https://upptime.js.org' target='_blank'>Upptime</a>."
